# Generated by Django 5.2.4 on 2025-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=0, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
