# Generated by Django 5.2.4 on 2025-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userorder_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='orderid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
