# Generated by Django 5.2.4 on 2025-09-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='test', upload_to='profiles'),
        ),
    ]
